# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "flatsat2"
BBFILE_PATTERN_flatsat2 = "^${LAYERDIR}/"
BBFILE_PRIORITY_flatsat2 = "9"

LAYERDEPENDS_flatsat2 = "core"
LAYERDEPENDS_flatsat2 += "xilinx"
LAYERDEPENDS_flatsat2 += "xilinx-tools"
LAYERDEPENDS_flatsat2 += "openembedded-layer"
LAYERDEPENDS_flatsat2 += "flatsat2-bsp"

LAYERSERIES_COMPAT_flatsat2 = "langdale"

LAYERTYPE_flatsat2 = "distro"
