# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "flatsat2-bsp"
BBFILE_PATTERN_flatsat2-bsp = "^${LAYERDIR}/"
BBFILE_PRIORITY_flatsat2-bsp = "9"

LAYERDEPENDS_flatsat2-bsp = "core"
LAYERDEPENDS_flatsat2-bsp += "xilinx"
LAYERDEPENDS_flatsat2-bsp += "xilinx-tools"
LAYERDEPENDS_flatsat2-bsp += "xilinx-standalone"
LAYERDEPENDS_flatsat2-bsp += "openembedded-layer"

LAYERSERIES_COMPAT_flatsat2-bsp = "langdale"

FLATSAT_BSP_LAYERDIR = "${LAYERDIR}"
