MACHINEOVERRIDES =. "${@['', 'microzed:']['microzed' != '${MACHINE}']}"

require conf/machine/include/flatsat-common.inc

HDF_BASE = "file://"
HDF_PATH = "${FLATSAT_BSP_LAYERDIR}/hw/xsa/flatsat2.xsa"

PACKAGE_EXTRA_ARCHS:append = "${@['', ' microzed']['microzed' != '${MACHINE}']}"
