MACHINEOVERRIDES =. "${@['', 'zedboard:']['zedboard' != '${MACHINE}']}"

require conf/machine/include/flatsat-common.inc

HDF_BASE = "file://"
HDF_PATH = "${FLATSAT_BSP_LAYERDIR}/hw/xsa/zed.xsa"

PACKAGE_EXTRA_ARCHS:append = "${@['', ' zedboard']['zedboard' != '${MACHINE}']}"
