#User Configuration

IMAGE_BOOT_FILES:zynq = "boot.bin boot.scr uImage"

INIT_MANAGER_DEFAULT:forcevariable = "systemd"

IMAGE_FEATURES:remove = "ssh-server-dropbear"

IMAGE_INSTALL:append = " nlohmann-json-dev libiio-dev \
                        libiio"

IMAGE_INSTALL:remove = "python-webserver" 
IMAGE_INSTALL:remove = "nano" 
IMAGE_INSTALL:remove = "iperf3" 

# The following installs source/development files of FlatSat2 packages
IMAGE_INSTALL:append = " fsatctl-src read-sensors-src"

PACKAGE_CLASSES = "package_ipk"
